### ISSUE TITLE
How to install librets to use it with python3.7.X

### ISSUE THREAD

**Issue by luiscastillocr** [NationalAssociationOfRealtors/libRETS#102]
We have our stack running on Ubuntu 18.04.4 LTS, we recently had the need to move away from 3.6.9(installed by default) and ungrade our servers to 3.7.X as you can image the most common way to make this upgrade is installing python3.7.x using a unix package manager as follows `sudo apt-get install python3.7 -y` this will create a new python executable somewhere in the system(most of the cases it is installed at /usr/local/lib/python3.7/) so my question is, is there a way you can install librets and point the binds to other python path other than the default?

Tried installing directly using pip but it didn't work
```
pip install git+https://github.com/NationalAssociationOfRealtors/libRETS.git@1.6.5#subdirectory=project/swig/python3
```

NOTE: moving to a different unix distro is not an option for now, that is because i am looking for an alternative to stay in the same Ubuntu version for now

Thanks

**Comment by jazzklein** [comment]
Since you are running on Linux, it is just a matter of rebuilding `libRETS` on that machine against the newer `python`. I don't recall who did the original `python3` setup for `swig`, but it may be possible you'll need to tweak https://github.com/NationalAssociationOfRealtors/libRETS/blob/master/project/build/python3.mk.
