### ISSUE TITLE
Help Installing Python Bindings

### ISSUE THREAD

**Issue by lgomez** [NationalAssociationOfRealtors/libRETS#13]
Hello all,

I'm not sure this project is being supported but I figured I'd try asking here.

I've been trying to get librets to work on a bare installation of Debian (wheezy) but my limited knowledge of C and python for that matter are making it hard. Here's how I'm setting this up:

```DockerFile
FROM debian:7.8

WORKDIR /root

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && apt-get upgrade -qq -y
RUN apt-get install -y apt-utils
RUN echo 'America/Los_Angeles' > /etc/timezone && dpkg-reconfigure tzdata
RUN apt-get install -y --fix-missing \
        build-essential \
        libboost-all-dev \
        curl \
        libcurl4-gnutls-dev \
        automake \
        autoconf \
        libtool \
        xsltproc \
        libexpat-dev \
        expat \
        default-jdk \
        wget \
        git \
        antlr \
        swig \
        python-dev

ENV CLASSPATH=".:/usr/share/java/antlr.jar:$CLASSPATH"
RUN alias antlr4='java -jar /usr/share/java/antlr.jar' && \
    alias grun='java org.antlr.v4.runtime.misc.TestRig'


RUN git clone https://github.com/NationalAssociationOfRealtors/libRETS.git && \
    cd libRETS/ && \
    ./autogen.sh && \
    ./configure \
        --prefix=/usr/bin \
        --disable-perl \
        --disable-ruby \
        --disable-java \
        --disable-dotnet \
        --disable-php \
        --disable-python3 \
        --enable-examples && \
    make && \
    make install
```

Now, for the purposes of this test I'm working under the `/root` directory so I end up with `/root/libRETS` whereas my test script is at `/app/test.py` and, for now simply contains:

```Python
# python
import sys
import librets
```

`python /app/test.py`, not surprisingly, exits because it can't find librets.

I've tried running `python setup.py install` from within `/root/libRETS/project/swig/python/` but that fails yielding:

```Shell
sys.platform: linux2
running install
running build
running build_py
file librets.py (for module librets) not found
file librets.py (for module librets) not found
running build_ext
building '_librets' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/root
creating build/temp.linux-x86_64-2.7/root/libRETS
creating build/temp.linux-x86_64-2.7/root/libRETS/project
creating build/temp.linux-x86_64-2.7/root/libRETS/project/swig
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c librets_wrap.cpp -o build/temp.linux-x86_64-2.7/librets_wrap.o -I/root/libRETS/project/librets/include -I/usr/include -I. -fPIC
gcc: error: librets_wrap.cpp: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command 'gcc' failed with exit status 4
```

Can anyone shed some light on this? I'm afraid I can't figure this out quickly enough to be useful for me.

Thank you!

**Comment by lgomez** [comment]
Note that I am running this in a Docker container.

Also, these are my running versions:
```Shell
python --version
Python 2.7.3

gcc --version
gcc (Debian 4.7.2-5) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

java -version
java version "1.6.0_34"
OpenJDK Runtime Environment (IcedTea6 1.13.6) (6b34-1.13.6-1~deb7u1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
```

**Comment by ktgeek** [comment]
2 things:

1) if everything built correctly, your resultant Python files should be in libRETS/build/swig/python

2) join the libRETS-users mailing list, there are a lot of really helpful people who can assist besides myself.  https://groups.realtors.org/sympa/info/librets-users

Keith




--
Keith T. Garner
kgarner@realtors.org<mailto:kgarner@realtors.org> 312-329-3294<tel:312-329-3294>
National Association of REALTORS®
VP - Information Technology Services

On Mar 6, 2015, at 4:20 PM, Luis G. Gómez <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello all,

I'm not sure this project is being supported but I figured I'd try asking here.

I've been trying to get librets to work on a bare installation of Debian (wheezy) but my limited knowledge of C and python for that matter are making it hard. Here's how I'm setting this up:

FROM debian:7.8

WORKDIR /root

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && apt-get upgrade -qq -y
RUN apt-get install -y apt-utils
RUN echo 'America/Los_Angeles' > /etc/timezone && dpkg-reconfigure tzdata
RUN apt-get install -y --fix-missing \
        build-essential \
        libboost-all-dev \
        curl \
        libcurl4-gnutls-dev \
        automake \
        autoconf \
        libtool \
        xsltproc \
        libexpat-dev \
        expat \
        default-jdk \
        wget \
        git \
        antlr \
        swig \
        python-dev

ENV CLASSPATH=".:/usr/share/java/antlr.jar:$CLASSPATH"
RUN alias antlr4='java -jar /usr/share/java/antlr.jar' && \
    alias grun='java org.antlr.v4.runtime.misc.TestRig'


RUN git clone https://github.com/NationalAssociationOfRealtors/libRETS.git && \
    cd libRETS/ && \
    ./autogen.sh && \
    ./configure \
        --prefix=/usr/bin \
        --disable-perl \
        --disable-ruby \
        --disable-java \
        --disable-dotnet \
        --disable-php \
        --disable-python3 \
        --enable-examples && \
    make && \
    make install

Now, for the purposes of this test I'm working under the /root directory so I end up with /root/libRETS whereas my test script is at /app/test.py and, for now simply contains:

# python
import sys
import librets

python /app/test.py, not surprisingly, exits because it can't find librets.

I've tried running python setup.py install from within /root/libRETS/project/swig/python/ but that fails yielding:

sys.platform: linux2
running install
running build
running build_py
file librets.py (for module librets) not found
file librets.py (for module librets) not found
running build_ext
building '_librets' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/root
creating build/temp.linux-x86_64-2.7/root/libRETS
creating build/temp.linux-x86_64-2.7/root/libRETS/project
creating build/temp.linux-x86_64-2.7/root/libRETS/project/swig
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c librets_wrap.cpp -o build/temp.linux-x86_64-2.7/librets_wrap.o -I/root/libRETS/project/librets/include -I/usr/include -I. -fPIC
gcc: error: librets_wrap.cpp: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command 'gcc' failed with exit status 4

Can anyone shed some light on this? I'm afraid I can't figure this out quickly enough to be useful for me.

Thank you!
