### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by mkhon** [NationalAssociationOfRealtors/libRETS#39]
1) Why OPENSSL_CFLAGS/LIBS is required? libcurl can be built with WinSSL (and is built with WinSSL on Windows by default)

2) Why not use auto-linking for boost libs (when .lib files are detected by compiler automatically). BOOST_XXX_LIB and all the related defines can be safely removed

**Comment by jazzklein** [comment]
> On Dec 23, 2016, at 9:35 AM, mkhon <notifications@github.com> wrote:
> 
> 	• Why OPENSSL_CFLAGS/LIBS is required? libcurl can be built with WinSSL (and is built with WinSSL on Windows by default)
> 
> 	• Why not use auto-linking for boost libs (when .lib files are detected by compiler automatically). BOOST_XXX_LIB and all the related defines can be safely removed

Primarily because I’m not a Windows developer and this is the only way I could manage to get it to build the last time I built it on Windows. If you have a better solution that doesn’t break the non Windows users, have at it (e.g. I won’t argue about changes to the various Windows makefiles, but I will have to verify source code changes).
