### ISSUE TITLE
RETS 1.8 Update transaction

### ISSUE THREAD

**Issue by ansarik** [NationalAssociationOfRealtors/libRETS#42]
Are there any plans to implement support for the RETS 1.8 Update transaction?
Specifically the inclusion of the required Action request argument

**Comment by jazzklein** [comment]
No plans, but someone else can surely do that and I'll be happy to merge the pull request.

**Comment by marwanhaddad** [comment]
@jazzklein has this issue been resolved? with this pull request https://github.com/NationalAssociationOfRealtors/libRETS/pull/48?

thanks

**Comment by jazzklein** [comment]
No, that just exposed some existing functionality to Windows.

**Comment by codenaked** [comment]
I'm happy to take a crack at adding support for supporting the "Action" request argument. What would be the best approach though?

1. If the RETS version is set to 1.8 then use "Action" instead of "Type".

This would follow the spec for 1.8, but this would break for any RETS servers out there that always require the "Type" parameter (even when using version 1.8).

2. Add an option that indicates whether to use "Action" or "Type".

This would allow the client to decide if the request should use "Action" or "Type" themselves. There could also be an "auto" option that would switch based on the RETS version. I'm assuming the "default" option should continue to use "Type" (as that is a break change)?

3. Add an option for setting the "Action" parameter independently of the "Type" parameter.

This is probably the easiest change that would fix this, but does mean the client could send requests with both "Type" and "Action" parameters. That may not be a bad thing.

**Comment by jazzklein** [comment]
@codenaked I've always tried to follow both the spec and the "do no harm" philosophy. So, anything that breaks existing usage should not be considered. I think your 3rd point is probably the best alternative.

I'll be happy to merge things if there are no other objections to what you do.

**Comment by codenaked** [comment]
@jazzklein - Any chance you can merge Darren Kopp's PR and put out a build? I would be eternally grateful! :-)
