### ISSUE TITLE
The type initializer for 'librets.libretsPINVOKE' threw an exception. 

### ISSUE THREAD

**Issue by abidCharlotte49er** [NationalAssociationOfRealtors/libRETS#78]
We have been seeing this issue since 2 weeks. We have had our MLS integration business logic using LibRETS for the last 6 years or so. I can confirm nothing changed related to this other than windows updates on the server. Below exception is thrown while instantiating RetsSession(URL). Did something change ?  I have referred to this Wiki but we have not seen this issue before our server environment is same as before and the reference link in FAQs is dead http://mail.crt.realtors.org/pipermail/librets-users/2008-September/001391.html  https://github.com/NationalAssociationOfRealtors/libRETS/wiki/FAQ 
 
**`RetsSession session = new RetsSession(RETSURL);`**

```
The type initializer for 'librets.libretsPINVOKE' threw an exception.

   at librets.libretsPINVOKE.new_RetsSession(String jarg1)
   at librets.RetsSession..ctor(String loginUrl)
The type initializer for 'SWIGExceptionHelper' threw an exception.

   at librets.libretsPINVOKE.SWIGExceptionHelper..ctor()
   at librets.libretsPINVOKE..cctor()---
```

**Comment by jazzklein** [comment]
Nothing changed on the `libRETS` side of things, especially since the Windows version hasn't be rebuilt in a long time. You say "other than Windows updates on the server", I'd suggest that Windows has changed something somewhere. Perhaps permissions/security was tightened and you may need to figure that out and relax it.
