### ISSUE TITLE
RETS or RESO Web API for keeping local database up to date?

### ISSUE THREAD

**Issue by carolinebeltran** [NationalAssociationOfRealtors/libRETS#83]
I hope that someone can guide me in the right direction.  I visited the specification page at https://www.reso.org/specifications/ and read:

**RETS** is at the end of its life cycle and is being replaced by a newer standard **RESO Web API**.

I'm totally new to this and need to download listed homes into a local database.  I've been given a user name / password to flexmls but I am concerned about the 'end of life' warning.

I understand that libRETS accesses data through RETS.  Instead of using libRETS, should I use Web API to obtain the data?  

P.S.  I plan to keep my local database periodically up to date for custom processing.  I don't plan to query Web API for my custom queries.

Thank you

**Comment by TRIBUSeric** [comment]
@carolinebeltran are you looking to get data for a single MLS or multiple?  If single, what MLS is it (Flex is the software provider to the MLS, not the MLS itself)?

**Comment by carolinebeltran** [comment]
Thank you so much for responding.  I have been granted access by GEPAR (El Paso, TX) MLS.  I am assuming that they use flexmls servers to store their data.  Anyway, flexmls gave me a user name and password and provided me with a link to RETS.  I need to replicate GEPAR listings to a local database for further manipulation.

**Comment by carolinebeltran** [comment]
This is the info that they sent me via email:

RETS Access provided to Greater El Paso MLS
For RETS technical support, visit https://www.flexmls.com/developers/rets/

**Comment by TRIBUSeric** [comment]
@carolinebeltran looks like that board is certified for WebAPI by RESO through Trestle.

![image](https://user-images.githubusercontent.com/3630033/64300256-68cf1c80-cf39-11e9-8cb8-180153a31a53.png)

However if your credentials are from Flex, its likely that they are for RETS not WebAPI 

You'll need to decide how you want to connect up.  If you want WebAPI - then you'll need to call back the MLS and have them set you up on Trestle instead of Flex.  At some point in the future RETS will go away.  So moving to WebAPI is ideal but not necessarily required.  Most consumers of MLS data do not make live queries to the WebAPI of the MLSs, they replicate the data locally.

We use both - WebAPI where we can and RETS for most MLSs since they don't have WebAPI yet or aren't fully setup to handle it.

One final thing - make sure to check that your license with El Paso allows for data manipulation - and allows you to create derivative data from it.  Your license might just be for IDX display.

**Comment by zBestData** [comment]
Over the past few years the Realtors have invested $$$ into putting their websites onto RETS, so I think it is going to go away anytime soon.  I don't think libRets is being supported like it once was and I am looking into replacing it with the .Net Core Version at: https://github.com/CrestApps/RetsConnector  

Our Importer is at :https://zbestdata.com/business-solutions/rets-idx-for-mls-and-real-estate

**Comment by carolinebeltran** [comment]
Thank you for the information above.  A 'data access setup fee' was paid and the license says that it is for display but can be queried, reordered, etc. but not modified.  Can I just ask one last question of you please, does the **URL above look incorrect to you**?  I am wondering why I get a ton of XML tags but no data between them.  I am wondering whether my URL is bad or flexmls has some access problem with my account.

**Comment by TRIBUSeric** [comment]
@carolinebeltran I'd recommend contacting the MLS to make sure the license will allow you to do derivative things with it.

As far as the data goes - I'll let someone else chime in here - but I think you're missing something in your query. perhaps a limit or another required variable.

**Comment by zBestData** [comment]
You cant to the request directly through your browse because the RETS when you login, the RETS server is going to give you a SessionKey and other values that you need to pass back to it in the http headers when you query the data.  So you will either need to use librets or code the httpRequest in C# to make the query.

**Comment by zBestData** [comment]
Also, I have found that the xml data is not always complete.  To get ALL the data, use CompatDecoded.

**Comment by carolinebeltran** [comment]
@zBestData thank you for the suggestions!

**Comment by zBestData** [comment]
@carolinebeltran   You're Welcome!

**Comment by zBestData** [comment]
One more thought..... you can verify your login at: https://retsmd.com/

**Comment by carolinebeltran** [comment]
I am assuming that flexmls RETS is not able to provide query results in XML format at this time because I get nothing but blank XML tags when I use the XML-STANDARD format.  If I use the COMPACT or COMPACT-DECODED format, I have no problems.

Kindest regards to Tribuseric and Zbestdata for helping me.
